import type { DemoPack } from '../types';
import { d, daysFromToday } from '../date-helpers';

const EMAIL_DOMAIN = 'demo.example.com';
const PREFIX = 'DMO';

const employees = [
  {
    employeeNumber: `${PREFIX}-UG-001`,
    firstName: 'Alex',
    lastName: 'Otieno',
    role: 'Operations Associate — Kampala',
    department: 'Operations',
    email: `employee@${EMAIL_DOMAIN}`,
    phone: '+256 700 200001',
    idNumber: `${PREFIX}-EMP-001`,
    kraPin: 'A012DMO001K',
    nssfNumber: `${PREFIX}-NSSF-001`,
    nhifNumber: `${PREFIX}-NHIF-001`,
    dateOfJoining: d(2022, 3, 15),
    baseSalary: 48000,
    allowances: [{ name: 'Transport', amount: 5000 }],
    bankName: 'Stanbic Bank Uganda',
    bankBranch: 'Kampala',
    bankAccountNumber: '9031001001',
  },
  {
    employeeNumber: `${PREFIX}-UG-002`,
    firstName: 'Sarah',
    lastName: 'Wanjiru',
    role: 'Operations Supervisor — Kampala',
    department: 'Operations',
    email: `sarah.wanjiru@${EMAIL_DOMAIN}`,
    phone: '+256 700 200002',
    idNumber: `${PREFIX}-EMP-002`,
    kraPin: 'A012DMO002K',
    nssfNumber: `${PREFIX}-NSSF-002`,
    nhifNumber: `${PREFIX}-NHIF-002`,
    dateOfJoining: d(2021, 7, 1),
    baseSalary: 78000,
    allowances: [{ name: 'Transport', amount: 6000 }],
    bankName: 'Centenary Bank',
    bankBranch: 'Kampala',
    bankAccountNumber: '9031001002',
  },
  {
    employeeNumber: `${PREFIX}-UG-003`,
    firstName: 'James',
    lastName: 'Okello',
    role: 'Sales Representative — Kampala',
    department: 'Sales',
    email: `james.okello@${EMAIL_DOMAIN}`,
    phone: '+256 700 200003',
    idNumber: `${PREFIX}-EMP-003`,
    kraPin: 'A012DMO003K',
    nssfNumber: `${PREFIX}-NSSF-003`,
    nhifNumber: `${PREFIX}-NHIF-003`,
    dateOfJoining: d(2023, 1, 10),
    baseSalary: 47000,
    allowances: [{ name: 'Commission', amount: 8000 }],
    bankName: 'Equity Bank Uganda',
    bankBranch: 'CBD',
    bankAccountNumber: '9031001003',
  },
  {
    employeeNumber: `${PREFIX}-UG-004`,
    firstName: 'Patricia',
    lastName: 'Namukasa',
    role: 'Logistics Coordinator — Entebbe',
    department: 'Logistics',
    email: `patricia.namukasa@${EMAIL_DOMAIN}`,
    phone: '+256 700 200004',
    idNumber: `${PREFIX}-EMP-004`,
    kraPin: 'A012DMO004K',
    nssfNumber: `${PREFIX}-NSSF-004`,
    nhifNumber: `${PREFIX}-NHIF-004`,
    dateOfJoining: d(2022, 11, 1),
    baseSalary: 98000,
    allowances: [{ name: 'Field', amount: 12000 }],
    bankName: 'Absa Bank Uganda',
    bankBranch: 'Entebbe',
    bankAccountNumber: '9031001004',
  },
  {
    employeeNumber: `${PREFIX}-UG-005`,
    firstName: 'Peter',
    lastName: 'Mugisha',
    role: 'Logistics Supervisor — Jinja Road',
    department: 'Logistics',
    email: `peter.mugisha@${EMAIL_DOMAIN}`,
    phone: '+256 700 200005',
    idNumber: `${PREFIX}-EMP-005`,
    kraPin: 'A012DMO005K',
    nssfNumber: `${PREFIX}-NSSF-005`,
    nhifNumber: `${PREFIX}-NHIF-005`,
    dateOfJoining: d(2021, 1, 10),
    baseSalary: 105000,
    allowances: [{ name: 'On-call', amount: 15000 }],
    bankName: 'DFCU Bank',
    bankBranch: 'Jinja Road',
    bankAccountNumber: '9031001005',
  },
  {
    employeeNumber: `${PREFIX}-KE-001`,
    firstName: 'Brian',
    lastName: 'Otieno',
    role: 'Operations Associate — Nairobi',
    department: 'Operations',
    email: `brian.otieno@${EMAIL_DOMAIN}`,
    phone: '+254 722 200006',
    idNumber: `${PREFIX}-EMP-006`,
    kraPin: 'A012DMO006K',
    nssfNumber: `${PREFIX}-NSSF-006`,
    nhifNumber: `${PREFIX}-NHIF-006`,
    dateOfJoining: d(2022, 5, 20),
    baseSalary: 52000,
    allowances: [{ name: 'Transport', amount: 6000 }],
    bankName: 'KCB Bank',
    bankBranch: 'Westlands',
    bankAccountNumber: '1100021006',
  },
  {
    employeeNumber: `${PREFIX}-KE-002`,
    firstName: 'Aisha',
    lastName: 'Wanjiru',
    role: 'Customer Service Lead — Nairobi',
    department: 'Customer Service',
    email: `aisha.wanjiru@${EMAIL_DOMAIN}`,
    phone: '+254 722 200007',
    idNumber: `${PREFIX}-EMP-007`,
    kraPin: 'A012DMO007K',
    nssfNumber: `${PREFIX}-NSSF-007`,
    nhifNumber: `${PREFIX}-NHIF-007`,
    dateOfJoining: d(2021, 9, 1),
    baseSalary: 88000,
    allowances: [{ name: 'Transport', amount: 7000 }],
    bankName: 'Equity Bank',
    bankBranch: 'Upper Hill',
    bankAccountNumber: '1100021007',
  },
  {
    employeeNumber: `${PREFIX}-KE-003`,
    firstName: 'Kevin',
    lastName: 'Kamau',
    role: 'IT Systems Analyst — Nairobi',
    department: 'IT & Systems',
    email: `kevin.kamau@${EMAIL_DOMAIN}`,
    phone: '+254 722 200008',
    idNumber: `${PREFIX}-EMP-008`,
    kraPin: 'A012DMO008K',
    nssfNumber: `${PREFIX}-NSSF-008`,
    nhifNumber: `${PREFIX}-NHIF-008`,
    dateOfJoining: d(2020, 4, 15),
    baseSalary: 145000,
    allowances: [{ name: 'Connectivity', amount: 10000 }],
    bankName: 'Co-operative Bank',
    bankBranch: 'Karen',
    bankAccountNumber: '1100021008',
  },
  {
    employeeNumber: `${PREFIX}-UG-006`,
    firstName: 'Diana',
    lastName: 'Namutebi',
    role: 'HR Business Partner — East Africa',
    department: 'Human Resources',
    email: `hr.demo@${EMAIL_DOMAIN}`,
    phone: '+256 700 200009',
    idNumber: `${PREFIX}-EMP-009`,
    kraPin: 'A012DMO009K',
    nssfNumber: `${PREFIX}-NSSF-009`,
    nhifNumber: `${PREFIX}-NHIF-009`,
    dateOfJoining: d(2019, 2, 1),
    baseSalary: 165000,
    allowances: [{ name: 'Travel', amount: 20000 }],
    bankName: 'Stanbic Bank Uganda',
    bankBranch: 'Kampala',
    bankAccountNumber: '9031001009',
  },
  {
    employeeNumber: `${PREFIX}-KE-004`,
    firstName: 'David',
    lastName: 'Ochieng',
    role: 'Finance Analyst — Nairobi',
    department: 'Finance',
    email: `finance.demo@${EMAIL_DOMAIN}`,
    phone: '+254 722 200010',
    idNumber: `${PREFIX}-EMP-010`,
    kraPin: 'A012DMO010K',
    nssfNumber: `${PREFIX}-NSSF-010`,
    nhifNumber: `${PREFIX}-NHIF-010`,
    dateOfJoining: d(2020, 8, 1),
    baseSalary: 155000,
    allowances: [{ name: 'Professional', amount: 12000 }],
    bankName: 'Standard Chartered',
    bankBranch: 'Upper Hill',
    bankAccountNumber: '1100021010',
  },
] as const;

export const genericPack: DemoPack = {
  id: 'generic',
  label: 'Generic HRIS Demo',
  workspace: {
    name: 'Demo Corporation',
    contactName: 'Diana Namutebi',
    contactEmail: `hr@${EMAIL_DOMAIN}`,
    contactPhone: '+254 709 000000',
    postalAddress: 'Multi-country workforce operations — Kenya and Uganda',
    county: 'East Africa (KE / UG)',
    employeeNumberPrefix: PREFIX,
    payrollFrequency: 'monthly',
    leavePayMode: 'none',
  },
  recruitmentEmployer: 'Demo Corporation',
  entities: {
    ke: {
      code: 'ke',
      legalName: 'Demo Corp Kenya Ltd',
      contactName: 'Diana Namutebi',
      contactEmail: `hr.ke@${EMAIL_DOMAIN}`,
      contactPhone: '+254 709 000000',
      postalAddress: 'Nairobi — operations, logistics, and support functions',
      county: 'Kenya',
      employeeNumberPrefix: `${PREFIX}-KE`,
      currency: 'KES',
    },
    ug: {
      code: 'ug',
      legalName: 'Demo Corp Uganda Ltd',
      contactName: 'Diana Namutebi',
      contactEmail: `hr.ug@${EMAIL_DOMAIN}`,
      contactPhone: '+256 414 000000',
      postalAddress: 'Kampala — operations, logistics, and support functions',
      county: 'Uganda',
      employeeNumberPrefix: `${PREFIX}-UG`,
      currency: 'UGX',
    },
  },
  legacyWorkspaceNames: ['Demo Corporation', 'Stabex International', 'Stabex Kenya Ltd'],
  departments: [
    'Operations',
    'Logistics',
    'Finance',
    'Human Resources',
    'Sales',
    'IT & Systems',
    'HSE',
    'Customer Service',
  ],
  employees: [...employees],
  careersJobs: [
    {
      title: 'Regional Operations Manager — East Africa',
      location: 'Nairobi, Kenya (Uganda travel)',
      type: 'Full Time',
      category: 'Operations Leadership',
      description:
        'Lead multi-site operations across Kenya and Uganda. Partner with supervisors, logistics, and HQ on KPIs, audits, and continuous improvement.',
      requirements: [
        '8+ years in operations or multi-site management',
        'Experience leading distributed teams',
        'Willingness to travel between Nairobi and Kampala monthly',
      ],
      responsibilities: [
        'Drive operational targets for the regional portfolio',
        'Lead quarterly reviews and corrective action plans',
        'Coach supervisors and align rota coverage with demand',
      ],
      benefits: ['Competitive package', 'Medical cover', 'Performance bonus'],
      skills: ['Operations', 'People Leadership', 'Stakeholder Management'],
      salary: { min: 280000, max: 420000, currency: 'KES' },
      salaryPublic: true,
      experience: '8+ years multi-site operations',
      education: "Bachelor's in Business or related field",
      minYearsExperience: 8,
      educationLevel: 'Bachelor',
      educationQualification: 'Business, Commerce, or Operations Management',
      requiredCertifications: null,
      deadlineDaysFromNow: 58,
    },
    {
      title: 'Operations Supervisor — Kampala',
      location: 'Kampala, Uganda',
      type: 'Full Time',
      category: 'Operations',
      description:
        'Supervise frontline teams: shift planning, quality controls, customer service, and day-to-day compliance with workplace standards.',
      requirements: [
        '3+ years as an operations or team supervisor',
        'Strong process and people management skills',
      ],
      responsibilities: [
        'Supervise daily operations and team performance',
        'Complete opening/closing checklists and incident reporting',
        'Coordinate with maintenance and escalate risks promptly',
      ],
      benefits: ['Medical cover', 'Career progression path'],
      skills: ['Team Leadership', 'Customer Service', 'Process Control'],
      salary: { min: 1800000, max: 2600000, currency: 'UGX' },
      salaryPublic: true,
      experience: '3+ years supervisory experience',
      education: 'Diploma or degree in business or related discipline',
      minYearsExperience: 3,
      educationLevel: 'Diploma',
      educationQualification: 'Business or Operations Management',
      requiredCertifications: null,
      deadlineDaysFromNow: 52,
    },
    {
      title: 'Logistics Coordinator — Nairobi',
      location: 'Nairobi, Kenya',
      type: 'Full Time',
      category: 'Logistics',
      description:
        'Coordinate inbound/outbound movements, schedules, and documentation. Ensure stock accuracy and operational readiness.',
      requirements: [
        '3+ years in logistics or supply chain coordination',
        'Strong Excel / ERP literacy',
      ],
      responsibilities: [
        'Plan daily schedules with operations and transport teams',
        'Maintain stock reconciliation and variance investigations',
        'Support safety briefings and compliance documentation',
      ],
      benefits: ['Medical cover', 'Transport allowance'],
      skills: ['Scheduling', 'Inventory Control', 'Documentation'],
      salary: { min: 120000, max: 180000, currency: 'KES' },
      salaryPublic: true,
      experience: '3+ years logistics coordination',
      education: 'Diploma or degree in Logistics or Business',
      minYearsExperience: 3,
      educationLevel: 'Diploma',
      educationQualification: 'Logistics, Operations, or Supply Chain',
      requiredCertifications: null,
      deadlineDaysFromNow: 48,
    },
    {
      title: 'HR Business Partner — Field Operations',
      location: 'Kampala, Uganda',
      type: 'Full Time',
      category: 'Human Resources',
      description:
        'Partner with operations leaders on workforce planning, performance cycles, and employee relations across a multi-country footprint.',
      requirements: [
        '5+ years HR BP or HR generalist experience',
        'Solid knowledge of Uganda employment practice',
      ],
      responsibilities: [
        'Support hiring, onboarding, and probation for frontline roles',
        'Coach managers on performance and employee relations',
        'Drive engagement programmes for shift-based teams',
      ],
      benefits: ['Medical cover', 'Learning budget'],
      skills: ['Employee Relations', 'Workforce Planning', 'HRIS'],
      salary: { min: 2400000, max: 3600000, currency: 'UGX' },
      salaryPublic: false,
      experience: '5+ years HR business partnering',
      education: "Bachelor's in HR or related field",
      minYearsExperience: 5,
      educationLevel: 'Bachelor',
      educationQualification: 'Human Resource Management or Psychology',
      requiredCertifications: null,
      deadlineDaysFromNow: 56,
    },
    {
      title: 'Finance Analyst — Operations',
      location: 'Nairobi, Kenya',
      type: 'Full Time',
      category: 'Finance',
      description:
        'Support management reporting, variance analysis, and month-end close for operations business lines.',
      requirements: [
        'CPA II minimum with 3+ years relevant experience',
        'Advanced Excel; ERP experience preferred',
      ],
      responsibilities: [
        'Produce weekly performance dashboards by region',
        'Support month-end close and audit documentation',
        'Partner with operations on KPI narratives',
      ],
      benefits: ['Medical cover', 'Study support', 'Bonus scheme'],
      skills: ['Financial Modelling', 'ERP', 'Reporting'],
      salary: { min: 130000, max: 190000, currency: 'KES' },
      salaryPublic: false,
      experience: '3+ years finance analysis',
      education: "Bachelor's in Finance or Accounting",
      minYearsExperience: 3,
      educationLevel: 'Bachelor',
      educationQualification: 'Commerce, Accounting, or Finance',
      requiredCertifications: 'CPA II or equivalent',
      deadlineDaysFromNow: 47,
    },
    {
      title: 'Graduate Trainee Programme — Operations',
      location: 'Kampala & Nairobi (rotations)',
      type: 'Full Time',
      category: 'Early Careers',
      description:
        'Two-year programme across operations, logistics shadowing, and HQ projects for graduates targeting supervisory roles.',
      requirements: [
        "Bachelor's completed within the last 24 months",
        'High energy and mobility between cities',
      ],
      responsibilities: [
        'Complete structured rotations with competency sign-offs',
        'Deliver a capstone operations improvement project',
        'Participate in team engagement activities',
      ],
      benefits: ['Mentorship', 'Medical cover', 'Programme stipend'],
      skills: ['Communication', 'Problem Solving', 'Teamwork'],
      salary: { min: 850000, max: 1200000, currency: 'UGX' },
      salaryPublic: true,
      experience: '0–1 years professional experience',
      education: "Bachelor's degree (any discipline)",
      minYearsExperience: 0,
      educationLevel: 'Bachelor',
      educationQualification: 'Open — strong academic record',
      requiredCertifications: null,
      deadlineDaysFromNow: 45,
    },
  ],
  credentials: [
    {
      email: `employee@${EMAIL_DOMAIN}`,
      category: 'training',
      name: 'Workplace Safety Certificate',
      number: 'WS-AO-001',
      authority: 'National Safety Board',
      issue: d(2023, 4, 1),
      expiry: d(2026, 8, 1),
      status: 'active',
    },
    {
      email: `employee@${EMAIL_DOMAIN}`,
      category: 'training',
      name: 'First Aid Certificate',
      number: 'FA-AO-002',
      authority: 'Red Cross',
      issue: d(2024, 1, 10),
      expiry: daysFromToday(10),
      status: 'expiring_soon',
    },
    {
      email: `sarah.wanjiru@${EMAIL_DOMAIN}`,
      category: 'training',
      name: 'Leadership Essentials',
      number: 'LE-SW-001',
      authority: 'HR Institute',
      issue: d(2022, 8, 1),
      expiry: d(2026, 2, 10),
      status: 'active',
    },
    {
      email: `james.okello@${EMAIL_DOMAIN}`,
      category: 'regulatory_compliance',
      name: 'Sales Compliance Certificate',
      number: 'SC-JO-001',
      authority: 'Trade Standards Agency',
      issue: d(2022, 6, 1),
      expiry: daysFromToday(-28),
      status: 'expired',
    },
    {
      email: `brian.otieno@${EMAIL_DOMAIN}`,
      category: 'training',
      name: 'Workplace Safety Certificate',
      number: 'WS-BO-001',
      authority: 'National Safety Board',
      issue: d(2023, 5, 1),
      expiry: d(2026, 10, 15),
      status: 'active',
    },
    {
      email: `aisha.wanjiru@${EMAIL_DOMAIN}`,
      category: 'training',
      name: 'Customer Service Excellence',
      number: 'CS-AW-001',
      authority: 'Service Quality Institute',
      issue: d(2024, 2, 1),
      expiry: daysFromToday(9),
      status: 'expiring_soon',
    },
  ],
  pipelineEmailDomain: 'pipeline.demo.example.com',
  jobReferenceCode: 'DMO',
  slugToken: 'dmo',
  demoPassword: 'Demo@2026!',
  staffUsers: {
    admin: { email: `demo@${EMAIL_DOMAIN}`, name: 'System Administrator' },
    hr: { email: `hr.demo@${EMAIL_DOMAIN}`, name: 'Diana Namutebi' },
    finance: { email: `finance.demo@${EMAIL_DOMAIN}`, name: 'David Ochieng' },
    ess: { email: `employee@${EMAIL_DOMAIN}`, name: 'Alex Otieno' },
    roleEmails: {
      brian: `brian.otieno@${EMAIL_DOMAIN}`,
      grace: `sarah.wanjiru@${EMAIL_DOMAIN}`,
      aisha: `aisha.wanjiru@${EMAIL_DOMAIN}`,
      robert: `james.okello@${EMAIL_DOMAIN}`,
      james: `finance.demo@${EMAIL_DOMAIN}`,
      paul: `peter.mugisha@${EMAIL_DOMAIN}`,
      moses: `employee@${EMAIL_DOMAIN}`,
      harriet: `patricia.namukasa@${EMAIL_DOMAIN}`,
      kevin: `kevin.kamau@${EMAIL_DOMAIN}`,
      diana: `hr.demo@${EMAIL_DOMAIN}`,
    },
  },
  interviewLocations: {
    video: 'https://meet.demo.example.com/interview-room',
    onsite: 'Demo Corp — Kampala HQ, Boardroom East (demo address)',
  },
  interviewBreakJobTitleIncludes: 'Operations Supervisor',
  companySetup: {
    appName: 'HRIS Demo',
    orgName: 'Demo Corporation',
    tagline: 'Human resources, payroll, recruitment, and workforce operations in one place.',
    wordmark: 'Demo Corporation',
    contactEmail: `hello@${EMAIL_DOMAIN}`,
    contactPhone: '+254 709 000000',
    contactAddress: 'Multi-country workforce operations — Kenya and Uganda',
    careersEmployerName: 'Demo Corporation',
    careersTagline: 'Human resources, payroll, recruitment, and workforce operations in one place.',
    staffLoginWelcomeTitle: 'Welcome to Demo Corporation',
    staffLoginWelcomeSubtitle: 'Sign in to manage your workforce',
    essLoginWelcomeTitle: 'Employee Self Service',
    essLoginWelcomeSubtitle: 'View payslips, leave, and personal details',
    payslipLegalName: 'Demo Corporation',
    emailFromName: 'Demo Corporation HR',
    publicFooterText:
      'Demo Corporation delivers workforce operations across Kenya and Uganda — HR, payroll, recruitment, and employee self-service in one platform.',
  },
};
