import { buildVerticalPackFromGeneric } from '../build-from-generic';
import { d, daysFromToday } from '../date-helpers';
import type { DemoEmployeeSeed, DemoPack } from '../types';

const DOMAIN = 'swiftfreight.imara.co.ke';
const PREFIX = 'SFE';
const ORG = 'SwiftFreight East Africa Ltd';

const base = buildVerticalPackFromGeneric({
  id: 'cargo-logistics',
  label: 'Cargo & logistics demo',
  orgName: ORG,
  emailDomain: DOMAIN,
  prefix: PREFIX,
  tagline: 'Fleet, warehouse, and dispatch operations — payroll and compliance for logistics teams.',
  publicFooterText:
    'SwiftFreight East Africa Ltd runs on Stride — driver payroll, shift rota, and statutory compliance for cargo operations.',
  departments: [
    'Fleet & Drivers',
    'Warehouse',
    'Dispatch',
    'Customs & Clearing',
    'Finance',
    'HR & Administration',
  ],
  departmentMap: {
    Operations: 'Dispatch',
    Sales: 'Dispatch',
    Logistics: 'Warehouse',
    Finance: 'Finance',
    'Human Resources': 'HR & Administration',
    ICT: 'Dispatch',
    'Customer Service': 'Dispatch',
    'IT & Systems': 'Dispatch',
    HSE: 'Fleet & Drivers',
  },
  postalAddress: 'Industrial Area, Nairobi — regional cargo hub',
});

const employees: DemoEmployeeSeed[] = [
  {
    employeeNumber: `${PREFIX}-KE-001`,
    firstName: 'Moses',
    lastName: 'Okello',
    role: 'Long-haul Driver — Mombasa corridor',
    department: 'Fleet & Drivers',
    email: `moses.okello@${DOMAIN}`,
    phone: '+254 722 410001',
    idNumber: `${PREFIX}-EMP-001`,
    kraPin: 'A012SFE001K',
    nssfNumber: `${PREFIX}-NSSF-001`,
    nhifNumber: `${PREFIX}-NHIF-001`,
    dateOfJoining: d(2021, 4, 12),
    baseSalary: 62000,
    allowances: [{ name: 'Trip', amount: 18000 }, { name: 'Per diem', amount: 8000 }],
    bankName: 'KCB Bank',
    bankBranch: 'Industrial Area',
    bankAccountNumber: '1200041001',
  },
  {
    employeeNumber: `${PREFIX}-KE-002`,
    firstName: 'Grace',
    lastName: 'Wanjiku',
    role: 'Dispatch Controller — Nairobi hub',
    department: 'Dispatch',
    email: `grace.wanjiku@${DOMAIN}`,
    phone: '+254 722 410002',
    idNumber: `${PREFIX}-EMP-002`,
    kraPin: 'A012SFE002K',
    nssfNumber: `${PREFIX}-NSSF-002`,
    nhifNumber: `${PREFIX}-NHIF-002`,
    dateOfJoining: d(2020, 8, 3),
    baseSalary: 98000,
    allowances: [{ name: 'Shift', amount: 12000 }, { name: 'Transport', amount: 8000 }],
    bankName: 'Equity Bank',
    bankBranch: 'Upper Hill',
    bankAccountNumber: '1200041002',
  },
  {
    employeeNumber: `${PREFIX}-KE-003`,
    firstName: 'Brian',
    lastName: 'Kipchoge',
    role: 'Warehouse Supervisor — Industrial Area',
    department: 'Warehouse',
    email: `brian.kipchoge@${DOMAIN}`,
    phone: '+254 722 410003',
    idNumber: `${PREFIX}-EMP-003`,
    kraPin: 'A012SFE003K',
    nssfNumber: `${PREFIX}-NSSF-003`,
    nhifNumber: `${PREFIX}-NHIF-003`,
    dateOfJoining: d(2019, 11, 1),
    baseSalary: 105000,
    allowances: [{ name: 'Responsibility', amount: 15000 }],
    bankName: 'Co-operative Bank',
    bankBranch: 'Mombasa Road',
    bankAccountNumber: '1200041003',
  },
  {
    employeeNumber: `${PREFIX}-KE-004`,
    firstName: 'Patricia',
    lastName: 'Achieng',
    role: 'Customs Clearing Officer',
    department: 'Customs & Clearing',
    email: `patricia.achieng@${DOMAIN}`,
    phone: '+254 722 410004',
    idNumber: `${PREFIX}-EMP-004`,
    kraPin: 'A012SFE004K',
    nssfNumber: `${PREFIX}-NSSF-004`,
    nhifNumber: `${PREFIX}-NHIF-004`,
    dateOfJoining: d(2022, 2, 14),
    baseSalary: 118000,
    allowances: [{ name: 'Professional', amount: 12000 }],
    bankName: 'Standard Chartered',
    bankBranch: 'Westlands',
    bankAccountNumber: '1200041004',
  },
  {
    employeeNumber: `${PREFIX}-KE-005`,
    firstName: 'James',
    lastName: 'Mutua',
    role: 'City Delivery Driver — last mile',
    department: 'Fleet & Drivers',
    email: `james.mutua@${DOMAIN}`,
    phone: '+254 722 410005',
    idNumber: `${PREFIX}-EMP-005`,
    kraPin: 'A012SFE005K',
    nssfNumber: `${PREFIX}-NSSF-005`,
    nhifNumber: `${PREFIX}-NHIF-005`,
    dateOfJoining: d(2023, 6, 1),
    baseSalary: 54000,
    allowances: [{ name: 'Trip', amount: 12000 }],
    bankName: 'Absa Bank',
    bankBranch: 'Embakasi',
    bankAccountNumber: '1200041005',
  },
  {
    employeeNumber: `${PREFIX}-KE-006`,
    firstName: 'Sarah',
    lastName: 'Njeri',
    role: 'Inventory Controller — bonded warehouse',
    department: 'Warehouse',
    email: `sarah.njeri@${DOMAIN}`,
    phone: '+254 722 410006',
    idNumber: `${PREFIX}-EMP-006`,
    kraPin: 'A012SFE006K',
    nssfNumber: `${PREFIX}-NSSF-006`,
    nhifNumber: `${PREFIX}-NHIF-006`,
    dateOfJoining: d(2021, 9, 20),
    baseSalary: 88000,
    allowances: [{ name: 'Transport', amount: 7000 }],
    bankName: 'NCBA Bank',
    bankBranch: 'Industrial Area',
    bankAccountNumber: '1200041006',
  },
  {
    employeeNumber: `${PREFIX}-KE-007`,
    firstName: 'Kevin',
    lastName: 'Omondi',
    role: 'Fleet Maintenance Coordinator',
    department: 'Fleet & Drivers',
    email: `kevin.omondi@${DOMAIN}`,
    phone: '+254 722 410007',
    idNumber: `${PREFIX}-EMP-007`,
    kraPin: 'A012SFE007K',
    nssfNumber: `${PREFIX}-NSSF-007`,
    nhifNumber: `${PREFIX}-NHIF-007`,
    dateOfJoining: d(2020, 3, 15),
    baseSalary: 92000,
    allowances: [{ name: 'On-call', amount: 10000 }],
    bankName: 'DTB Bank',
    bankBranch: 'Mombasa Road',
    bankAccountNumber: '1200041007',
  },
  {
    employeeNumber: `${PREFIX}-KE-008`,
    firstName: 'Diana',
    lastName: 'Namutebi',
    role: 'HR & Payroll Officer',
    department: 'HR & Administration',
    email: `hr@${DOMAIN}`,
    phone: '+254 722 410008',
    idNumber: `${PREFIX}-EMP-008`,
    kraPin: 'A012SFE008K',
    nssfNumber: `${PREFIX}-NSSF-008`,
    nhifNumber: `${PREFIX}-NHIF-008`,
    dateOfJoining: d(2018, 1, 10),
    baseSalary: 155000,
    allowances: [{ name: 'Travel', amount: 15000 }],
    bankName: 'Stanbic Bank',
    bankBranch: 'Chiromo',
    bankAccountNumber: '1200041008',
  },
  {
    employeeNumber: `${PREFIX}-KE-009`,
    firstName: 'David',
    lastName: 'Ochieng',
    role: 'Finance Analyst — operations',
    department: 'Finance',
    email: `finance@${DOMAIN}`,
    phone: '+254 722 410009',
    idNumber: `${PREFIX}-EMP-009`,
    kraPin: 'A012SFE009K',
    nssfNumber: `${PREFIX}-NSSF-009`,
    nhifNumber: `${PREFIX}-NHIF-009`,
    dateOfJoining: d(2019, 7, 1),
    baseSalary: 148000,
    allowances: [{ name: 'Professional', amount: 12000 }],
    bankName: 'I&M Bank',
    bankBranch: 'Upper Hill',
    bankAccountNumber: '1200041009',
  },
  {
    employeeNumber: `${PREFIX}-KE-010`,
    firstName: 'Amina',
    lastName: 'Njeri',
    role: 'Operations Manager — East Africa',
    department: 'Dispatch',
    email: `admin@imara.co.ke`,
    phone: '+254 722 410010',
    idNumber: `${PREFIX}-EMP-010`,
    kraPin: 'A012SFE010K',
    nssfNumber: `${PREFIX}-NSSF-010`,
    nhifNumber: `${PREFIX}-NHIF-010`,
    dateOfJoining: d(2017, 5, 1),
    baseSalary: 220000,
    allowances: [{ name: 'Responsibility', amount: 35000 }],
    bankName: 'KCB Bank',
    bankBranch: 'Karen',
    bankAccountNumber: '1200041010',
  },
];

const careersJobs = [
  {
    title: 'Long-haul Truck Driver — Mombasa corridor',
    location: 'Nairobi, Kenya',
    type: 'Full Time',
    category: 'Fleet & Drivers',
    description:
      'Join SwiftFreight’s regional fleet moving containerised and break-bulk cargo between Nairobi, Mombasa, and border points. Safety-first culture with telematics and journey management.',
    requirements: [
      'Valid CE driving licence with 5+ years articulated vehicle experience',
      'Clean traffic record and medical fitness certificate',
      'Experience with EAC border documentation preferred',
    ],
    responsibilities: [
      'Execute assigned routes per journey management plan',
      'Complete pre-trip and post-trip vehicle inspections',
      'Maintain delivery notes, PODs, and fuel logs in the ESS app',
    ],
    benefits: ['Trip allowances', 'Medical cover', 'Driver safety training'],
    skills: ['Defensive driving', 'Route knowledge', 'Documentation'],
    salary: { min: 55000, max: 75000, currency: 'KES' },
    salaryPublic: true,
    experience: '5+ years long-haul driving',
    education: 'KCSE; professional driving certification',
    minYearsExperience: 5,
    educationLevel: 'Certificate',
    educationQualification: 'Professional driving / logistics',
    requiredCertifications: 'Valid CE licence, PSV badge, medical certificate',
    deadlineDaysFromNow: 42,
  },
  {
    title: 'Warehouse Supervisor — Industrial Area',
    location: 'Nairobi, Kenya',
    type: 'Full Time',
    category: 'Warehouse',
    description:
      'Lead inbound receiving, put-away, and dispatch for a high-throughput cargo warehouse serving regional freight clients.',
    requirements: [
      '3+ years warehouse or 3PL supervision',
      'WMS literacy and stock reconciliation experience',
      'Forklift licence an advantage',
    ],
    responsibilities: [
      'Supervise shift teams for loading, picking, and dispatch',
      'Own daily stock counts and variance investigations',
      'Enforce HSE standards for lifting and vehicle loading bays',
    ],
    benefits: ['Medical cover', 'Performance bonus', 'Transport allowance'],
    skills: ['Inventory control', 'Team leadership', 'HSE awareness'],
    salary: { min: 95000, max: 130000, currency: 'KES' },
    salaryPublic: true,
    experience: '3+ years warehouse supervision',
    education: 'Diploma in Supply Chain or Logistics',
    minYearsExperience: 3,
    educationLevel: 'Diploma',
    educationQualification: 'Logistics, Supply Chain, or Operations',
    requiredCertifications: null,
    deadlineDaysFromNow: 38,
  },
  {
    title: 'Customs Clearing Officer',
    location: 'Nairobi, Kenya',
    type: 'Full Time',
    category: 'Customs & Clearing',
    description:
      'Process import/export declarations, coordinate with KRA and port agents, and keep clients informed on clearance timelines.',
    requirements: [
      'KRA customs agent licence or equivalent clearing certification',
      '2+ years in freight forwarding or clearing',
      'Strong knowledge of HS codes and EAC trade protocols',
    ],
    responsibilities: [
      'Prepare and lodge customs entries and supporting documents',
      'Track shipments through port and inland container depots',
      'Escalate holds, inspections, and duty queries to clients',
    ],
    benefits: ['Medical cover', 'Professional membership support'],
    skills: ['Customs compliance', 'Documentation', 'Client communication'],
    salary: { min: 110000, max: 160000, currency: 'KES' },
    salaryPublic: false,
    experience: '2+ years customs clearing',
    education: 'Diploma or degree in Clearing & Forwarding',
    minYearsExperience: 2,
    educationLevel: 'Diploma',
    educationQualification: 'Clearing, Freight Forwarding, or International Trade',
    requiredCertifications: 'KRA customs agent licence',
    deadlineDaysFromNow: 45,
  },
  {
    title: 'Dispatch Controller — Nairobi hub',
    location: 'Nairobi, Kenya',
    type: 'Full Time',
    category: 'Dispatch',
    description:
      'Coordinate daily fleet movements, driver assignments, and customer ETAs from the Nairobi control tower.',
    requirements: [
      '2+ years in transport control or logistics coordination',
      'Comfortable with GPS/telematics dashboards',
      'Strong communication under peak-season pressure',
    ],
    responsibilities: [
      'Assign routes and monitor in-transit exceptions',
      'Liaise with drivers, warehouse, and customer service',
      'Publish peak-season rota patterns with operations leadership',
    ],
    benefits: ['Shift allowance', 'Medical cover'],
    skills: ['Scheduling', 'Telematics', 'Customer service'],
    salary: { min: 85000, max: 115000, currency: 'KES' },
    salaryPublic: true,
    experience: '2+ years dispatch or control room',
    education: 'Diploma in Logistics or Business',
    minYearsExperience: 2,
    educationLevel: 'Diploma',
    educationQualification: 'Logistics, Transport, or Operations',
    requiredCertifications: null,
    deadlineDaysFromNow: 35,
  },
];

const credentials = [
  {
    email: `moses.okello@${DOMAIN}`,
    category: 'regulatory_compliance' as const,
    name: 'Driving Licence — Class CE',
    number: 'DL-CE-MO-8842',
    authority: 'NTSA Kenya',
    issue: d(2022, 3, 1),
    expiry: d(2027, 3, 1),
    status: 'active' as const,
  },
  {
    email: `moses.okello@${DOMAIN}`,
    category: 'regulatory_compliance' as const,
    name: 'PSV Badge — Goods vehicle',
    number: 'PSV-MO-2210',
    authority: 'NTSA Kenya',
    issue: d(2023, 1, 15),
    expiry: daysFromToday(18),
    status: 'expiring_soon' as const,
  },
  {
    email: `moses.okello@${DOMAIN}`,
    category: 'training' as const,
    name: 'ADR Dangerous Goods Awareness',
    number: 'ADR-MO-004',
    authority: 'Fleet Safety Kenya',
    issue: d(2024, 6, 1),
    expiry: d(2027, 6, 1),
    status: 'active' as const,
  },
  {
    email: `james.mutua@${DOMAIN}`,
    category: 'regulatory_compliance' as const,
    name: 'Driving Licence — Class C',
    number: 'DL-C-JM-5521',
    authority: 'NTSA Kenya',
    issue: d(2021, 8, 1),
    expiry: daysFromToday(-14),
    status: 'expired' as const,
  },
  {
    email: `patricia.achieng@${DOMAIN}`,
    category: 'regulatory_compliance' as const,
    name: 'KRA Customs Agent Licence',
    number: 'KRA-CA-PA-1198',
    authority: 'Kenya Revenue Authority',
    issue: d(2020, 4, 1),
    expiry: d(2026, 4, 1),
    status: 'active' as const,
  },
  {
    email: `brian.kipchoge@${DOMAIN}`,
    category: 'training' as const,
    name: 'Forklift Operator Certificate',
    number: 'FLT-BK-032',
    authority: 'OSHA Kenya',
    issue: d(2023, 9, 1),
    expiry: d(2026, 9, 1),
    status: 'active' as const,
  },
  {
    email: `kevin.omondi@${DOMAIN}`,
    category: 'training' as const,
    name: 'Defensive Driving Refresher',
    number: 'DDR-KO-018',
    authority: 'Fleet Safety Kenya',
    issue: d(2024, 2, 1),
    expiry: daysFromToday(8),
    status: 'expiring_soon' as const,
  },
];

export const cargoLogisticsPack: DemoPack = {
  ...base,
  employees,
  careersJobs,
  credentials,
  staffUsers: {
    ...base.staffUsers,
    admin: { email: 'admin@imara.co.ke', name: 'Amina Njeri' },
    hr: { email: `hr@${DOMAIN}`, name: 'Diana Namutebi' },
    finance: { email: `finance@${DOMAIN}`, name: 'David Ochieng' },
    ess: { email: `moses.okello@${DOMAIN}`, name: 'Moses Okello' },
    roleEmails: {
      brian: `brian.kipchoge@${DOMAIN}`,
      grace: `grace.wanjiku@${DOMAIN}`,
      aisha: `sarah.njeri@${DOMAIN}`,
      robert: `james.mutua@${DOMAIN}`,
      james: `finance@${DOMAIN}`,
      paul: `kevin.omondi@${DOMAIN}`,
      moses: `moses.okello@${DOMAIN}`,
      harriet: `patricia.achieng@${DOMAIN}`,
      kevin: `kevin.omondi@${DOMAIN}`,
      diana: `hr@${DOMAIN}`,
    },
  },
  interviewBreakJobTitleIncludes: 'Driver',
};
